[package]
name = "game_cheetah"
version = "0.1.0"
authors = ["Mike Krüger <mkrueger@posteo.de>"]
edition = "2021"
rust-version = "1.60"

[dependencies]
egui = "0.19.0"
egui_extras = "0.19.0"
eframe = { version = "0.19.0", features = ["persistence"] }
process-memory = "0.4.0"
proc-maps = "0.2.1"
sysinfo = "0.26.4"
needle = "0.1.1"
threadpool = "1.0"
sudo = "0.5"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]