name: Windows Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: game_cheetah_osx
        path: target/release/game_cheetah